# Generated by Django 4.1.7 on 2023-03-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
